#include "Core.h"

#define CORE_MATRIX_ASSERT(expression) static_assert((expression), #expression)

constexpr bool CoreMatrixTextEqual(const char* left, const char* right)
{
    return *left == *right && (*left == '\0' || CoreMatrixTextEqual(left + 1, right + 1));
}

#define CORE_MATRIX_TEXT(actual, expected) CORE_MATRIX_ASSERT(CoreMatrixTextEqual(actual, expected))

#ifndef CORE_OS_LINUX
#define CORE_OS_LINUX 0
#endif
#ifndef CORE_OS_UNIX
#define CORE_OS_UNIX 0
#endif

#if CORE_MATRIX_SCENARIO == 1
CORE_MATRIX_ASSERT(CORE_ENABLE_ARCHITECTURE == 0);
CORE_MATRIX_ASSERT(CORE_ENABLE_COMPILER == 0);
CORE_MATRIX_ASSERT(CORE_ENABLE_HARDWARE == 0);
CORE_MATRIX_ASSERT(CORE_ENABLE_LANGUAGE == 0);
CORE_MATRIX_ASSERT(CORE_ENABLE_LIBRARY == 0);
CORE_MATRIX_ASSERT(CORE_ENABLE_PLATFORM == 0);
CORE_MATRIX_ASSERT(CORE_ENABLE_OTHER == 0);
CORE_MATRIX_TEXT(CORE_ARCH_NAME, "Unknown");
CORE_MATRIX_TEXT(CORE_COMP_NAME, "Unknown");
CORE_MATRIX_TEXT(CORE_LANG_NAME, "Unknown");
CORE_MATRIX_TEXT(CORE_LIB_STD_NAME, "Unknown");
CORE_MATRIX_TEXT(CORE_LIB_C_NAME, "Unknown");
CORE_MATRIX_TEXT(CORE_OS_NAME, "Unknown");
CORE_MATRIX_TEXT(CORE_PLAT_NAME, "Unknown");
CORE_MATRIX_TEXT(CORE_ENDIAN_NAME, "Unknown");
CORE_MATRIX_TEXT(CORE_ARCH_WORD_BITS_NAME, "Unknown");
CORE_MATRIX_TEXT(CORE_HW_SIMD_NAME, "Unknown");

#elif CORE_MATRIX_SCENARIO == 2
CORE_MATRIX_ASSERT(CORE_ARCH_WASM32 == CORE_VERSION_NUMBER_AVAILABLE);
CORE_MATRIX_ASSERT(CORE_ARCH_WORD_BITS == 32);
CORE_MATRIX_TEXT(CORE_ARCH_NAME, "WASM 32");
CORE_MATRIX_ASSERT(CORE_PLAT_WEB == CORE_VERSION_NUMBER_AVAILABLE);
CORE_MATRIX_TEXT(CORE_PLAT_NAME, "Web");

#elif CORE_MATRIX_SCENARIO == 3
CORE_MATRIX_ASSERT(CORE_ARCH_ARM == CORE_VERSION_NUMBER(8, 0, 0));
CORE_MATRIX_ASSERT(CORE_ARCH_WORD_BITS == 64);
CORE_MATRIX_TEXT(CORE_ARCH_NAME, "ARM");
CORE_MATRIX_ASSERT(CORE_HW_SIMD_ARM == CORE_HW_SIMD_ARM_NEON_VERSION);
CORE_MATRIX_TEXT(CORE_HW_SIMD_NAME, "ARM SIMD");

#elif CORE_MATRIX_SCENARIO == 4
CORE_MATRIX_ASSERT(CORE_ARCH_RISCV == CORE_VERSION_NUMBER_AVAILABLE);
CORE_MATRIX_ASSERT(CORE_ARCH_WORD_BITS == 64);
CORE_MATRIX_ASSERT(CORE_ENDIAN_LITTLE_BYTE == CORE_VERSION_NUMBER_AVAILABLE);
CORE_MATRIX_TEXT(CORE_ENDIAN_NAME, "Byte-Swapped Little-Endian");

#elif CORE_MATRIX_SCENARIO == 5
CORE_MATRIX_ASSERT(CORE_ARCH_PPC != 0);
CORE_MATRIX_ASSERT(CORE_ARCH_PPC_64 != 0);
CORE_MATRIX_ASSERT(CORE_ARCH_WORD_BITS == 64);
CORE_MATRIX_TEXT(CORE_ARCH_NAME, "PowerPC64");

#elif CORE_MATRIX_SCENARIO == 6
CORE_MATRIX_ASSERT(CORE_ARCH_SH == CORE_VERSION_NUMBER(2, 0, 0));
CORE_MATRIX_ASSERT(CORE_ARCH_WORD_BITS == 16);
CORE_MATRIX_TEXT(CORE_ARCH_NAME, "SuperH");

#elif CORE_MATRIX_SCENARIO == 7
CORE_MATRIX_ASSERT(CORE_ARCH_LOONGARCH != 0);
CORE_MATRIX_ASSERT(CORE_ARCH_WORD_BITS == 64);
CORE_MATRIX_ASSERT(CORE_ENDIAN_LITTLE_BYTE != 0);

#elif CORE_MATRIX_SCENARIO == 8
CORE_MATRIX_ASSERT(CORE_COMP_CLANG == CORE_VERSION_NUMBER(17, 2, 1));
CORE_MATRIX_ASSERT(CORE_COMP_GCC_EMULATED == CORE_VERSION_NUMBER(13, 2, 1));
CORE_MATRIX_TEXT(CORE_COMP_NAME, "Clang");

#elif CORE_MATRIX_SCENARIO == 9
CORE_MATRIX_ASSERT(CORE_COMP_EMSCRIPTEN == CORE_VERSION_NUMBER(18, 1, 2));
CORE_MATRIX_ASSERT(CORE_COMP_CLANG_EMULATED == CORE_VERSION_NUMBER(18, 1, 2));
CORE_MATRIX_ASSERT(CORE_COMP_GCC_EMULATED == CORE_VERSION_NUMBER(12, 3, 0));
CORE_MATRIX_TEXT(CORE_COMP_NAME, "Emscripten");

#elif CORE_MATRIX_SCENARIO == 10
CORE_MATRIX_ASSERT(CORE_COMP_DEC != 0);
CORE_MATRIX_TEXT(CORE_COMP_NAME, "Compaq C/C++");

#elif CORE_MATRIX_SCENARIO == 11
CORE_MATRIX_ASSERT(CORE_COMP_DIAB == CORE_PREDEF_MAKE_10_VRPP(4567));
CORE_MATRIX_TEXT(CORE_COMP_NAME, "Diab C/C++");

#elif CORE_MATRIX_SCENARIO == 12
CORE_MATRIX_ASSERT(CORE_LANG_STDCPP == CORE_PREDEF_MAKE_YYYYMM(199711L));
CORE_MATRIX_ASSERT(CORE_LANG_STDCPP_CPP98 != 0);
CORE_MATRIX_TEXT(CORE_LANG_STDCPP_NAME, "Standard C++98");

#elif CORE_MATRIX_SCENARIO == 13
CORE_MATRIX_ASSERT(CORE_LANG_STDCPPCLI == CORE_PREDEF_MAKE_YYYYMM(201103L));
CORE_MATRIX_TEXT(CORE_LANG_NAME, "C++/CLI");

#elif CORE_MATRIX_SCENARIO == 14
CORE_MATRIX_ASSERT(CORE_LANG_STDECPP != 0);
CORE_MATRIX_TEXT(CORE_LANG_NAME, "Embedded C++");

#elif CORE_MATRIX_SCENARIO == 15
CORE_MATRIX_ASSERT(CORE_LIB_STD_GNU > 0);
CORE_MATRIX_TEXT(CORE_LIB_STD_NAME, "GNU");
CORE_MATRIX_ASSERT(CORE_LIB_C_GNU > 0);
CORE_MATRIX_TEXT(CORE_LIB_C_NAME, "GNU");

#elif CORE_MATRIX_SCENARIO == 16
CORE_MATRIX_ASSERT(CORE_LIB_STD_STLPORT == CORE_VERSION_NUMBER(5, 2, 1));
CORE_MATRIX_TEXT(CORE_LIB_STD_NAME, "STLport");
CORE_MATRIX_ASSERT(CORE_LIB_C_VMS == CORE_PREDEF_MAKE_10_VVRR0PP00(80320000));
CORE_MATRIX_TEXT(CORE_LIB_C_NAME, "VMS");

#elif CORE_MATRIX_SCENARIO == 17
CORE_MATRIX_ASSERT(CORE_OS_ANDROID != 0);
CORE_MATRIX_ASSERT(!CORE_OS_LINUX);
CORE_MATRIX_TEXT(CORE_OS_NAME, "Android");
CORE_MATRIX_ASSERT(CORE_PLAT_ANDROID != 0);
CORE_MATRIX_TEXT(CORE_PLAT_NAME, "Android");

#elif CORE_MATRIX_SCENARIO == 18
CORE_MATRIX_ASSERT(CORE_OS_LINUX != 0);
CORE_MATRIX_ASSERT(!CORE_OS_UNIX);
CORE_MATRIX_TEXT(CORE_OS_NAME, "Linux");

#elif CORE_MATRIX_SCENARIO == 19
CORE_MATRIX_ASSERT(CORE_OS_BSD_FREE == CORE_VERSION_NUMBER(13, 2, 1));
CORE_MATRIX_ASSERT(CORE_OS_BSD != 0);
CORE_MATRIX_TEXT(CORE_OS_NAME, "Free BSD");

#elif CORE_MATRIX_SCENARIO == 20
CORE_MATRIX_ASSERT(CORE_OS_BSD_OPEN == CORE_VERSION_NUMBER(6, 9, 0));
CORE_MATRIX_ASSERT(CORE_OS_BSD != 0);
CORE_MATRIX_TEXT(CORE_OS_NAME, "OpenBSD");

#elif CORE_MATRIX_SCENARIO == 21
CORE_MATRIX_ASSERT(CORE_OS_MACOS == CORE_VERSION_NUMBER(10, 0, 0));
CORE_MATRIX_ASSERT(!CORE_OS_UNIX);
CORE_MATRIX_TEXT(CORE_OS_NAME, "Mac OS");

#elif CORE_MATRIX_SCENARIO == 22
CORE_MATRIX_ASSERT(CORE_OS_UNIX != 0);
CORE_MATRIX_TEXT(CORE_OS_NAME, "Unix Environment");

#elif CORE_MATRIX_SCENARIO == 23
CORE_MATRIX_ASSERT(CORE_PLAT_MINGW == CORE_VERSION_NUMBER(11, 2, 0));
CORE_MATRIX_ASSERT(CORE_PLAT_MINGW32_EMULATED == CORE_VERSION_NUMBER(11, 2, 0));
CORE_MATRIX_TEXT(CORE_PLAT_NAME, "MinGW (any variety)");

#elif CORE_MATRIX_SCENARIO == 24
CORE_MATRIX_ASSERT(CORE_PLAT_WINDOWS_UWP != 0);
CORE_MATRIX_ASSERT(CORE_PLAT_WINDOWS_PHONE != 0);
CORE_MATRIX_ASSERT(CORE_PLAT_WINDOWS_RUNTIME != 0);
CORE_MATRIX_TEXT(CORE_PLAT_NAME, "Windows Runtime");

#elif CORE_MATRIX_SCENARIO == 25
CORE_MATRIX_ASSERT(CORE_PLAT_WINDOWS_UWP != 0);
CORE_MATRIX_ASSERT(CORE_PLAT_WINDOWS_SERVER != 0);
CORE_MATRIX_TEXT(CORE_PLAT_NAME, "Windows Server");

#elif CORE_MATRIX_SCENARIO == 26
CORE_MATRIX_ASSERT(CORE_ENDIAN_BIG_BYTE != 0);
CORE_MATRIX_TEXT(CORE_ENDIAN_NAME, "Byte-Swapped Big-Endian");

#elif CORE_MATRIX_SCENARIO == 27
CORE_MATRIX_ASSERT(CORE_ENDIAN_LITTLE_BYTE != 0);
CORE_MATRIX_TEXT(CORE_ENDIAN_NAME, "Byte-Swapped Little-Endian");

#elif CORE_MATRIX_SCENARIO == 28
CORE_MATRIX_ASSERT(CORE_ENDIAN_LITTLE_WORD != 0);
CORE_MATRIX_TEXT(CORE_ENDIAN_NAME, "Word-Swapped Little-Endian");

#elif CORE_MATRIX_SCENARIO == 29
CORE_MATRIX_ASSERT(CORE_ENDIAN_BIG_BYTE != 0);
CORE_MATRIX_ASSERT(CORE_ARCH_M68K != 0);

#elif CORE_MATRIX_SCENARIO == 30
CORE_MATRIX_ASSERT(CORE_ENDIAN_LITTLE_BYTE != 0);
CORE_MATRIX_ASSERT(CORE_ARCH_X64 != 0);

#elif CORE_MATRIX_SCENARIO == 31
CORE_MATRIX_ASSERT(CORE_HW_SIMD_X86 == CORE_HW_SIMD_X86_AVX2_VERSION);
CORE_MATRIX_ASSERT(CORE_HW_SIMD_X86_AMD == CORE_HW_SIMD_X86_AVX2_VERSION);
CORE_MATRIX_TEXT(CORE_HW_SIMD_NAME, "x86 (AMD) SIMD");

#elif CORE_MATRIX_SCENARIO == 32
CORE_MATRIX_ASSERT(CORE_HW_SIMD_PPC == CORE_VERSION_NUMBER(2, 0, 0));
CORE_MATRIX_TEXT(CORE_HW_SIMD_NAME, "PPC SIMD");

#elif CORE_MATRIX_SCENARIO == 33
CORE_MATRIX_ASSERT(CORE_ENABLE_PLATFORM == 0);
CORE_MATRIX_ASSERT(CORE_ENABLE_OTHER == 0);
CORE_MATRIX_TEXT(CORE_OS_NAME, "Unknown");
CORE_MATRIX_TEXT(CORE_ENDIAN_NAME, "Unknown");
CORE_MATRIX_TEXT(CORE_ARCH_WORD_BITS_NAME, "Unknown");

#else
#error "Unknown CORE_MATRIX_SCENARIO"
#endif

int main()
{
    return 0;
}
