#ifndef CORE_TEST_WINAPIFAMILY_H
#define CORE_TEST_WINAPIFAMILY_H
#ifndef WINAPI_FAMILY_DESKTOP_APP
#define WINAPI_FAMILY_DESKTOP_APP 1
#endif
#ifndef WINAPI_FAMILY_PHONE_APP
#define WINAPI_FAMILY_PHONE_APP 2
#endif
#ifndef WINAPI_FAMILY_PC_APP
#define WINAPI_FAMILY_PC_APP 3
#endif
#ifndef WINAPI_FAMILY_APP
#define WINAPI_FAMILY_APP 4
#endif
#ifndef WINAPI_FAMILY_SERVER
#define WINAPI_FAMILY_SERVER 5
#endif
#ifndef WINAPI_FAMILY_SYSTEM
#define WINAPI_FAMILY_SYSTEM 6
#endif
#endif
